# Site settings
name: Hannah Ji
title: Hannah Ji | Machine Learning Engineer and Data Scientist
description: Mathematically-oriented machine learning and computer vision researcher.
url: https://hannahji01.github.io/
baseurl: ''
email: hannah.ji@yale.edu
cover: https://hannahji01.github.io/img/og.png
logo: https://hannahji01.github.io/img/emojis/technologist.png
social:
  - title: email
    url: mailto:hannah.ji@yale.edu
  - title: github
    url: https://github.com/hannahji01
  - title: linkedin
    url: https://www.linkedin.com/in/hannahji001/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
